// scripts/build-words.mjs
// Phase 1b — Refine + merge (deterministic, re-runnable).
//
// Reads the normalized source files produced by Phase 1a, discovered from
// data/sources/<level>/*.json (skipping *_flagged.json), and emits the
// immutable runtime dataset:
//   data/words.json      (array of Word, sorted by id)
//   data/changelog.json  (array of { lemma, from, to } corrections)
//
// No network, no LLM. All translations for Goethe-only entries are baked into
// GOETHE_EN below (all A1 vocabulary). Running this repeatedly is idempotent.

import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'data', 'sources');

const VALID_LEVELS = ['a1', 'a2', 'b1'];

// Known filename → source tag, kept for backward compatibility with the
// existing sources[] values already baked into words.json. Unknown files
// (future A2/B1 sources) fall back to their filename.
const TAG_MAP = {
  'telc-a1-1': 'telc-a1.1',
  'telc-a1-2': 'telc-a1.2',
  'goethe-a1': 'goethe',
};

function discoverSources() {
  const sources = [];
  for (const level of readdirSync(SRC).sort()) {
    if (!VALID_LEVELS.includes(level)) continue;
    const dir = join(SRC, level);
    if (!statSync(dir).isDirectory()) continue;
    for (const file of readdirSync(dir).sort()) {
      if (!file.endsWith('.json') || file.includes('_flagged')) continue;
      const base = file.replace(/\.json$/, '');
      const tag = TAG_MAP[base] ?? base;
      sources.push({ file: join(level, file), level, tag });
    }
  }
  return sources;
}

// --- slug / lemma normalization -------------------------------------------

function slug(lemma) {
  return lemma
    .toLowerCase()
    .replace(/ä/g, 'ae')
    .replace(/ö/g, 'oe')
    .replace(/ü/g, 'ue')
    .replace(/ß/g, 'ss')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

// Apply a Goethe-style plural suffix notation to a noun stem.
function applyPluralNotation(stem, note) {
  const n = note.trim();
  if (/^-(e?n|s|e|er)$/.test(n)) return stem + n.slice(1);
  return null;
}

// A few Phase-1a Goethe rows leaked column notation into the lemma. Strip it
// here (1b is the refine step) and recover the plural where it was the leak.
function normalizeLemma(raw) {
  let lemma = raw.trim();
  let pluralFromNote = null;

  // "Herr; -en" → lemma "Herr", plural "Herren"
  const semi = lemma.match(/^(.*?)\s*;\s*(-\S+)\s*$/);
  if (semi) {
    lemma = semi[1].trim();
    pluralFromNote = applyPluralNotation(lemma, semi[2]);
  }

  // "Ende (Sg)" / "Ende (Sg.)" → lemma "Ende", singular-only (plural null)
  let singularOnly = false;
  const sg = lemma.match(/^(.*?)\s*\((Sg|Pl)\.?\)\s*$/i);
  if (sg) {
    lemma = sg[1].trim();
    singularOnly = true;
  }

  return { lemma, pluralFromNote, singularOnly };
}

// --- corrections ("only obvious", per CLAUDE.md) ---------------------------
// Keyed by normalized lemma. Verified against the source text layer.

const CORRECTIONS = {
  zahlen: 'to pay', // was "to count"
  Schnupfen: 'cold / runny nose', // was "to sniff" (it's der Schnupfen, a noun)
  kreativ: 'creative', // was "people" (row misaligned with die Leute)
  verzögern: 'to delay', // was "to hesitate"
  Position: 'position', // was "police station"; alphabetically Polizei/Position/Post — German is right, gloss wrong
};

// --- English for Goethe-only entries (no English in the Goethe source) -----
// Keyed by normalized lemma. Every Goethe-only entry must appear here.

const GOETHE_EN = {
  abfahren: 'to depart / leave',
  abgeben: 'to hand in / drop off',
  abholen: 'to pick up / collect',
  Ahnung: 'idea / clue',
  alle: 'all / everyone',
  allein: 'alone',
  Alter: 'age',
  'ander-': 'other',
  Anfang: 'beginning / start',
  Angst: 'fear',
  ankommen: 'to arrive',
  Anruf: 'phone call',
  Anrufbeantworter: 'answering machine',
  Appetit: 'appetite',
  arbeitslos: 'unemployed',
  Artikel: 'article',
  aufmachen: 'to open',
  aufpassen: 'to pay attention / watch out',
  aufräumen: 'to tidy up',
  'auf sein': 'to be open',
  Ausflug: 'excursion / outing',
  Ausland: 'abroad / foreign countries',
  aussehen: 'to look / appear',
  'aus sein': 'to be over / finished',
  aussteigen: 'to get off / out',
  Automat: 'vending machine',
  Baby: 'baby',
  Bahnsteig: 'platform',
  Band: 'band',
  Basketball: 'basketball',
  basteln: 'to do crafts / make things',
  bedeuten: 'to mean',
  besetzt: 'occupied / taken',
  besonders: 'especially / particularly',
  beste: 'best',
  CD: 'CD',
  Comic: 'comic',
  danken: 'to thank',
  dein: 'your',
  'der, die, das': 'the (definite article)',
  deshalb: 'therefore / that is why',
  dick: 'fat / thick',
  Disco: 'disco / club',
  dumm: 'stupid / dumb',
  Durst: 'thirst',
  duschen: 'to shower',
  ein: 'a / an / one',
  Eins: 'a one (top grade)',
  einsteigen: 'to get in / board',
  'einverstanden sein': 'to agree / be in agreement',
  Ende: 'end',
  entschuldigen: 'to excuse / apologise',
  euer: 'your (plural)',
  Fach: 'subject / compartment',
  Fahrplan: 'timetable / schedule',
  Fehler: 'mistake / error',
  Ferien: 'holidays / vacation',
  'fertig sein': 'to be finished / ready',
  fliegen: 'to fly',
  Flugzeug: 'aeroplane',
  Fluss: 'river',
  Fotoapparat: 'camera',
  Fuß: 'foot',
  geboren: 'born',
  genug: 'enough',
  Gepäck: 'luggage / baggage',
  Geschichte: 'story / history',
  'geschlossen sein': 'to be closed',
  gewinnen: 'to win',
  Glück: 'luck / happiness',
  Glückwunsch: 'congratulations',
  Großeltern: 'grandparents',
  Handy: 'mobile phone',
  Herr: 'gentleman / Mr',
  herzlich: 'warm / cordial',
  hoffen: 'to hope',
  hoffentlich: 'hopefully',
  hübsch: 'pretty',
  Internet: 'internet',
  jeder: 'every / each / everyone',
  Jugendliche: 'young people / teenagers',
  jung: 'young',
  Junge: 'boy',
  Kakao: 'cocoa / hot chocolate',
  Kamera: 'camera',
  Katze: 'cat',
  kein: 'no / not any',
  kennenlernen: 'to get to know / meet',
  Kiosk: 'kiosk / newsstand',
  Klassenarbeit: 'class test',
  Klavier: 'piano',
  lachen: 'to laugh',
  lange: 'for a long time',
  laufen: 'to run / walk',
  leicht: 'easy / light',
  leid: 'sorry (es tut mir leid)',
  lieb: 'dear / kind',
  lieber: 'rather / preferably',
  'Lieblings-': 'favourite',
  Lust: 'desire / inclination',
  Mädchen: 'girl',
  Mail: 'email',
  Mal: 'time (occurrence)',
  Marktplatz: 'market square',
  mein: 'my',
  Mineralwasser: 'mineral water',
  mitkommen: 'to come along',
  mitmachen: 'to join in / take part',
  mitnehmen: 'to take along',
  möglich: 'possible',
  Nachricht: 'message / news',
  nächste: 'next',
  niemand: 'nobody / no one',
  normal: 'normal',
  Note: 'grade / mark',
  Nummer: 'number',
  offen: 'open',
  Ohrring: 'earring',
  Paket: 'package / parcel',
  passieren: 'to happen',
  Pferd: 'horse',
  Poster: 'poster',
  Quatsch: 'nonsense',
  Quiz: 'quiz',
  Rad: 'bicycle / wheel',
  Rätsel: 'puzzle / riddle',
  'recht haben': 'to be right',
  Regen: 'rain',
  reiten: 'to ride (a horse)',
  Ring: 'ring',
  schon: 'already',
  schwer: 'difficult / heavy',
  schwimmen: 'to swim',
  See: 'lake',
  'spazieren gehen': 'to go for a walk',
  Spielplatz: 'playground',
  Süßigkeiten: 'sweets / candy',
  sympathisch: 'likeable / nice',
  Taschengeld: 'pocket money / allowance',
  'Tennis spielen': 'to play tennis',
  Theater: 'theatre',
  Thema: 'topic / theme',
  Tier: 'animal',
  traurig: 'sad',
  'U-Bahn': 'underground / subway',
  üben: 'to practise',
  'und so weiter': 'and so on (etc.)',
  unser: 'our',
  verrückt: 'crazy',
  viel: 'much / a lot',
  'vorstellen (sich)': 'to introduce (oneself)',
  wahr: 'true',
  Wald: 'forest / woods',
  wandern: 'to hike',
  wecken: 'to wake (someone) up',
  'weh tun': 'to hurt',
  weit: 'far',
  'welch-': 'which',
  wenig: 'little / few',
  wiederholen: 'to repeat',
  'wie viel': 'how much',
  wirklich: 'really',
  wunderbar: 'wonderful',
  Wurst: 'sausage',
  'zum Geburtstag': "for one's birthday",
  'zum Beispiel': 'for example',
  zumachen: 'to close / shut',
  'zu sein': 'to be closed',

  // --- A2 (goethe-a2) ---
  ab: 'from / starting',
  aber: 'but',
  abfliegen: 'to depart (by plane)',
  Achtung: 'attention',
  Adresse: 'address',
  aktiv: 'active',
  'all-': 'all',
  als: 'than',
  also: 'so',
  alt: 'old',
  Ampel: 'traffic light',
  an: 'at / on',
  'an sein / aus sein': 'to be on / to be off',
  anfangen: 'to start / begin',
  Angebot: 'offer',
  anmachen: 'to turn on',
  'anmelden (sich)': 'to register',
  Anmeldung: 'registration',
  anrufen: 'to call',
  ansehen: 'to watch / look at',
  Antwort: 'answer',
  antworten: 'to answer',
  Anzeige: 'advertisement',
  Anzug: 'suit',
  Apfel: 'apple',
  Apotheke: 'pharmacy',
  Apparat: 'device',
  Arbeit: 'work',
  arbeiten: 'to work',
  arm: 'poor',
  auch: 'also',
  auf: 'on',
  'auf jeden Fall': 'in any case',
  aufregend: 'exciting',
  'aufräumen': 'to tidy up',
  aufstehen: 'to get up',
  Auge: 'eye',
  aus: 'from / out of',
  Ausbildung: 'training / education',
  'ausfüllen': 'to fill out',
  Ausgang: 'exit',
  ausgehen: 'to go out',
  Auskunft: 'information',
  auspacken: 'to unpack',
  'ausruhen (sich)': 'to rest',
  aussprechen: 'to pronounce',
  Ausstellung: 'exhibition',
  austauschen: 'to exchange',
  austragen: 'to deliver',
  Auto: 'car',
  Autobahn: 'highway',
  automatisch: 'automatic',
  'außerdem': 'besides / in addition',
  'außerhalb': 'outside',
  Babysitter: 'babysitter',
  backen: 'to bake',
  Bad: 'bathroom',
  baden: 'to bathe',
  Bahn: 'train',
  Bahnhof: 'train station',
  bald: 'soon',
  Balkon: 'balcony',
  Ball: 'ball',
  Banane: 'banana',
  Bank: 'bank',
  Bauch: 'belly / stomach',
  bauen: 'to build',
  Baum: 'tree',
  Baustelle: 'construction site',
  beantworten: 'to answer',
  'bedanken (sich)': 'to thank',
  'beeilen (sich)': 'to hurry',
  beginnen: 'to begin',
  bei: 'at / near',
  beide: 'both',
  Bein: 'leg',
  bekannt: 'well-known',
  Bekannte: 'acquaintance',
  bekommen: 'to get / receive',
  beliebt: 'popular',
  benutzen: 'to use',
  bequem: 'comfortable',
  Berg: 'mountain',
  berichten: 'to report',
  Beruf: 'profession',
  'berühmt': 'famous',
  Bescheid: 'notice / news',
  beschreiben: 'to describe',
  'beschweren (sich)': 'to complain',
  bestehen: 'to pass (an exam)',
  'bestätigen': 'to confirm',
  Besuch: 'visit',
  besuchen: 'to visit',
  Bett: 'bed',
  'bewerben (sich)': 'to apply (for a job)',
  Bewerbung: 'application',
  'bewölkt': 'cloudy',
  bezahlen: 'to pay',
  Bibliothek: 'library',
  Bier: 'beer',
  Bild: 'picture',
  billig: 'cheap',
  Birne: 'pear',
  bis: 'until',
  bisschen: 'a little / a bit',
  bitte: 'please',
  bitter: 'bitter',
  Blatt: 'sheet (of paper) / leaf',
  bleiben: 'to stay',
  Bleistift: 'pencil',
  Blog: 'blog',
  Blume: 'flower',
  Bluse: 'blouse',
  'blöd': 'stupid / silly',
  Bohne: 'bean',
  brauchen: 'to need',
  Brief: 'letter',
  Briefmarke: 'stamp',
  Brille: 'glasses',
  bringen: 'to bring',
  Brot: 'bread',
  'Brötchen': 'bread roll',
  'Brücke': 'bridge',
  Buch: 'book',
  Buchstabe: 'letter (of the alphabet)',
  buchstabieren: 'to spell',
  Bus: 'bus',
  Butter: 'butter',
  'Bäckerei': 'bakery',
  'böse': 'angry / mad',
  'Büro': 'office',
  Cafeteria: 'cafeteria',
  'Café': 'café',
  Chef: 'boss',
  Chefin: 'boss',
  Club: 'club',
  Computer: 'computer',
  Creme: 'cream',
  da: 'there',
  dabei: 'along / present',
  dagegen: 'against it',
  daneben: 'next to it / beside it',
  Dank: 'thanks',
  danke: 'thank you',
  dann: 'then',
  Datum: 'date',
  dauern: 'to last / take (time)',
  denken: 'to think',
  denn: 'because / for',
  direkt: 'directly',
  Disko: 'disco / club',
  doch: 'yes (contradicting) / but',
  Doppelzimmer: 'double room',
  Dorf: 'village',
  dort: 'there',
  'draußen': 'outside',
  dringend: 'urgent',
  drinnen: 'inside',
  Drucker: 'printer',
  dunkel: 'dark',
  durch: 'through',
  Dusche: 'shower',
  'duschen (sich)': 'to shower',
  'dürfen': 'to be allowed to / may',
  'E-Book': 'e-book',
  'E-Mail': 'email',
  Ehefrau: 'wife',
  Ehemann: 'husband',
  Ehepartner: 'spouse',
  Ei: 'egg',
  'eigen-': 'own',
  eigentlich: 'actually',
  eilig: 'in a hurry / urgent',
  'ein paar': 'a few',
  einfach: 'simple / easy',
  Eingang: 'entrance',
  'einig-': 'some / several',
  einkaufen: 'to shop / go shopping',
  Einkaufszentrum: 'shopping center',
  einladen: 'to invite',
  Einladung: 'invitation',
  einmal: 'once / one time',
  einpacken: 'to pack',
  'eintragen (sich)': 'to sign up / register',
  einverstanden: 'agreed / in agreement',
  'einzel-': 'individual / single',
  Eis: 'ice cream',
  'Empfänger': 'recipient',
  enden: 'to end',
  endlich: 'finally',
  eng: 'tight / narrow',
  Entschuldigung: 'excuse / apology',
  Erdgeschoss: 'ground floor',
  Erfahrung: 'experience',
  'erinnern (sich)': 'to remember',
  'erklären': 'to explain',
  'erkältet sein': 'to have a cold',
  erlauben: 'to allow',
  Erlaubnis: 'permission',
  'erlaubt sein': 'to be allowed',
  'Ermäßigung': 'discount',
  erst: 'not until / only',
  Erwachsene: 'adult',
  'erzählen': 'to tell',
  essen: 'to eat',
  etwas: 'something',
  Fahrkarte: 'ticket',
  Fahrrad: 'bicycle',
  fallen: 'to fall',
  falsch: 'wrong',
  Familie: 'family',
  Familienname: 'surname',
  Fan: 'fan',
  Farbe: 'color',
  fast: 'almost',
  faul: 'lazy',
  Feier: 'party / celebration',
  feiern: 'to celebrate',
  Fenster: 'window',
  fernsehen: 'to watch TV',
  Fernseher: 'television',
  Fest: 'celebration / festival',
  Festival: 'festival',
  fett: 'fatty / greasy',
  Fieber: 'fever',
  Film: 'movie / film',
  finden: 'to find',
  Firma: 'company',
  Fisch: 'fish',
  'fit sein': 'to be fit',
  Flasche: 'bottle',
  Fleisch: 'meat',
  'fleißig': 'hardworking / diligent',
  Flug: 'flight',
  Flughafen: 'airport',
  Formular: 'form',
  Foto: 'photo',
  fotografieren: 'to photograph',
  Frage: 'question',
  fragen: 'to ask',
  Frau: 'woman / Mrs.',
  frei: 'free',
  fremd: 'foreign / unfamiliar',
  'freuen (sich)': 'to be happy / pleased',
  Freund: 'friend',
  freundlich: 'friendly',
  frisch: 'fresh',
  froh: 'glad / happy',
  'früh': 'early',
  'früher': 'earlier / in the past',
  'Frühstück': 'breakfast',
  'frühstücken': 'to have breakfast',
  Fundsachen: 'lost and found',
  furchtbar: 'terrible / awful',
  'Fuß': 'foot',
  'Fußball': 'soccer / football',
  'fühlen (sich)': 'to feel',
  'Führerschein': 'driver\'s license',
  'Führung': 'guided tour',
  'für': 'for',
  ganz: 'whole / intact',
  Garage: 'garage',
  Garten: 'garden',
  Gast: 'guest',
  geben: 'to give',
  Geburtsjahr: 'year of birth',
  Geburtsort: 'place of birth',
  geehrt: 'dear / honored',
  gefallen: 'to please / like',
  'gefährlich': 'dangerous',
  gegen: 'against',
  Gegenteil: 'opposite',
  'gegenüber': 'opposite / across from',
  Gehalt: 'salary',
  gehen: 'to go / work (function)',
  Geld: 'money',
  'Gemüse': 'vegetables',
  genau: 'exact / exactly',
  'Gepäck': 'luggage',
  gerade: 'just / straight',
  geradeaus: 'straight ahead',
  gern: 'gladly',
  'Gerät': 'device / appliance',
  Geschenk: 'gift',
  'Geschäft': 'shop / business',
  Gesicht: 'face',
  'Gespräch': 'conversation',
  gestern: 'yesterday',
  Gesundheit: 'health',
  'Getränk': 'drink',
  Gewitter: 'thunderstorm',
  Gitarre: 'guitar',
  Glas: 'glass',
  glauben: 'to believe / think',
  gleich: 'right away / equal',
  Gleis: 'platform / track',
  'glücklich': 'happy',
  gratulieren: 'to congratulate',
  grillen: 'to grill / barbecue',
  Grippe: 'flu',
  'groß': 'big / tall',
  Gruppe: 'group',
  'Gruß': 'greeting',
  'Größe': 'size',
  gut: 'good',
  'gültig sein': 'to be valid',
  'günstig': 'cheap / good value',
  Haar: 'hair',
  haben: 'to have',
  Halle: 'hall',
  hallo: 'hello',
  Hals: 'neck / throat',
  halten: 'to stop',
  Haltestelle: 'stop (bus/train)',
  Hamburger: 'hamburger',
  Hand: 'hand',
  Handtuch: 'towel',
  hart: 'hard',
  Hauptstadt: 'capital city',
  Haus: 'house',
  Haushalt: 'household',
  Heft: 'notebook',
  Heimat: 'home country / homeland',
  heiraten: 'to marry',
  Heizung: 'heating',
  'heiß': 'hot',
  'heißen': 'to be called',
  helfen: 'to help',
  hell: 'bright / light',
  Hemd: 'shirt',
  'her/her-/-her': 'here / toward the speaker',
  'heraus/raus': 'out',
  Herd: 'stove',
  'herein/rein': 'in / come in',
  herstellen: 'to produce / manufacture',
  heute: 'today',
  hier: 'here',
  Hilfe: 'help',
  Himmel: 'sky / heaven',
  'hin/hin-/-hin': 'there / away from the speaker',
  hinten: 'at the back',
  hinter: 'behind',
  Hobby: 'hobby',
  Hochzeit: 'wedding',
  Homepage: 'homepage',
  Hose: 'trousers / pants',
  Hotel: 'hotel',
  Hund: 'dog',
  Hunger: 'hunger',
  husten: 'to cough',
  'Hähnchen': 'chicken',
  'hängen': 'to hang',
  'hässlich': 'ugly',
  'hören': 'to hear / listen',
  Idee: 'idea',
  immer: 'always',
  in: 'in',
  Information: 'information',
  Insel: 'island',
  Instrument: 'instrument',
  intelligent: 'intelligent',
  interessant: 'interesting',
  Interesse: 'interest',
  'interessieren (sich)': 'to be interested (in)',
  Interview: 'interview',
  ja: 'yes',
  Jacke: 'jacket',
  Jeans: 'jeans',
  jetzt: 'now',
  Job: 'job',
  joggen: 'to jog',
  Jugendherberge: 'youth hostel',
  Kaffee: 'coffee',
  Kalender: 'calendar',
  kalt: 'cold',
  kaputt: 'broken',
  Karte: 'card',
  Kartoffel: 'potato',
  Kasse: 'checkout / cash register',
  kaufen: 'to buy',
  Kaufhaus: 'department store',
  Keller: 'cellar',
  kennen: 'to know',
  Kette: 'necklace',
  Kind: 'child',
  Kindergarten: 'kindergarten',
  Kino: 'cinema',
  Kirche: 'church',
  klappen: 'to work out',
  klar: 'sure / clear',
  Kleid: 'dress',
  Kleidung: 'clothing',
  klein: 'small',
  Klub: 'club',
  klug: 'smart / clever',
  kochen: 'to cook',
  Koffer: 'suitcase',
  Kollege: 'colleague',
  Kollegin: 'colleague',
  komisch: 'funny / strange',
  kommen: 'to come',
  Kontakt: 'contact',
  Konzert: 'concert',
  Kopf: 'head',
  Kosmetik: 'cosmetics',
  kosten: 'to cost',
  krank: 'sick',
  Krankenhaus: 'hospital',
  Krankenkasse: 'health insurance',
  Krankheit: 'illness',
  Kredit: 'loan / credit',
  Kreuzung: 'intersection',
  kriegen: 'to get / receive',
  Krimi: 'crime novel / thriller',
  Kuchen: 'cake',
  Kultur: 'culture',
  Kunde: 'customer',
  Kundin: 'customer',
  Kurs: 'course',
  kurz: 'short',
  'Käse': 'cheese',
  'können': 'can / to be able to',
  'Körper': 'body',
  'Küche': 'kitchen',
  'kühl': 'cool',
  'Kühlschrank': 'fridge',
  'kümmern (sich)': 'to take care of',
  'kündigen': 'to quit / give notice',
  Lampe: 'lamp',
  Land: 'country',
  Landschaft: 'landscape',
  lang: 'long',
  langsam: 'slow',
  langweilig: 'boring',
  lassen: 'to let / leave',
  laut: 'loud',
  leben: 'to live',
  Lebensmittel: 'groceries / food',
  leer: 'empty',
  leider: 'unfortunately',
  leidtun: 'to be sorry',
  leise: 'quiet',
  lernen: 'to learn',
  lesen: 'to read',
  'letzt-': 'last',
  Leute: 'people',
  Licht: 'light',
  'lieb-': 'dear / kind',
  lieben: 'to love',
  Lied: 'song',
  liegen: 'to lie / be located',
  Link: 'link',
  links: 'left / on the left',
  Lokal: 'restaurant / pub',
  lustig: 'funny',
  'Lüge': 'lie',
  'lügen': 'to lie',
  machen: 'to do / make',
  Magen: 'stomach',
  Mailbox: 'mailbox / voicemail',
  mal: 'just / for once',
  man: 'one / you (impersonal)',
  'manch-': 'some / many a',
  manchmal: 'sometimes',
  Mann: 'man / husband',
  Mannschaft: 'team',
  Mantel: 'coat',
  Markt: 'market',
  Maschine: 'machine',
  Medikament: 'medicine',
  Meer: 'sea',
  mehr: 'more',
  meinen: 'to mean',
  'meist-': 'most',
  meistens: 'mostly / usually',
  Mensch: 'person / human',
  merken: 'to remember / notice',
  Messe: 'trade fair',
  Miete: 'rent',
  mieten: 'to rent',
  Milch: 'milk',
  mindestens: 'at least',
  Mitarbeiter: 'employee',
  mitspielen: 'to join in / play along',
  Mittagessen: 'lunch',
  Mitte: 'middle',
  Mittel: 'remedy / means',
  Mobiltelefon: 'mobile phone',
  Mode: 'fashion',
  modern: 'modern',
  Moment: 'moment',
  morgen: 'tomorrow',
  Motor: 'engine',
  Motorroller: 'scooter',
  Mund: 'mouth',
  Museum: 'museum',
  Musik: 'music',
  'Möbel': 'furniture',
  'möchten': 'would like',
  'mögen': 'to like',
  'möglich': 'possible',
  'müde': 'tired',
  'Müll': 'trash / garbage',
  'müssen': 'must / to have to',
  'Mütze': 'cap / hat',
  nach: 'to / after',
  Nachbar: 'neighbor',
  Name: 'name',
  nass: 'wet',
  Natur: 'nature',
  'natürlich': 'naturally / of course',
  neben: 'next to',
  nebenan: 'next door',
  neblig: 'foggy',
  nehmen: 'to take',
  nein: 'no',
  nett: 'nice',
  neu: 'new',
  nicht: 'not',
  nichts: 'nothing',
  nie: 'never',
  nirgends: 'nowhere',
  noch: 'still / yet',
  Notiz: 'note',
  notwendig: 'necessary',
  Nudel: 'noodle',
  nur: 'only',
  'nächste': 'next',
  'nützlich': 'useful',
  Obst: 'fruit',
  oder: 'or',
  oft: 'often',
  ohne: 'without',
  Ohr: 'ear',
  online: 'online',
  Orange: 'orange',
  Ordnung: 'order',
  organisieren: 'to organize',
  Ort: 'place',
  Paar: 'pair / couple',
  packen: 'to pack',
  Papier: 'paper',
  Papiere: 'documents / papers',
  'Parfüm': 'perfume',
  Park: 'park',
  parken: 'to park',
  Partner: 'partner',
  Partnerin: 'partner (female)',
  Party: 'party',
  Pass: 'passport',
  passen: 'to fit',
  Passwort: 'password',
  Pause: 'break',
  Person: 'person',
  Pflanze: 'plant',
  Pizza: 'pizza',
  Plakat: 'poster',
  Plan: 'map / plan',
  planen: 'to plan',
  Platz: 'seat / place',
  Polizei: 'police',
  'Pommes frites': 'fries',
  Portion: 'portion',
  Post: 'post office',
  Postkarte: 'postcard',
  Postleitzahl: 'postal code',
  Praktikum: 'internship',
  praktisch: 'practical',
  Praxis: 'doctor\'s office',
  Preis: 'price',
  pro: 'per',
  probieren: 'to try',
  Problem: 'problem',
  Produkt: 'product',
  Projekt: 'project',
  Prospekt: 'brochure',
  'prüfen': 'to check',
  Pullover: 'sweater',
  putzen: 'to clean',
  'pünktlich': 'on time',
  'Qualität': 'quality',
  Radio: 'radio',
  raten: 'to advise / guess',
  Rathaus: 'town hall',
  rauchen: 'to smoke',
  Raum: 'room',
  rechnen: 'to calculate',
  rechts: 'right',
  reden: 'to talk',
  regnen: 'to rain',
  Reifen: 'tire',
  Reihe: 'row',
  Reinigung: 'dry cleaner\'s',
  Reis: 'rice',
  Reise: 'trip',
  'Reisebüro': 'travel agency',
  'Reiseführer': 'travel guide',
  renovieren: 'to renovate',
  Rentner: 'retiree',
  Rentnerin: 'retiree (female)',
  Reparatur: 'repair',
  reparieren: 'to repair',
  Rest: 'rest / remainder',
  Restaurant: 'restaurant',
  Rezept: 'recipe',
  Rezeption: 'reception desk',
  richtig: 'correct',
  riechen: 'to smell',
  Rind: 'beef / cattle',
  Rock: 'skirt',
  romantisch: 'romantic',
  Rose: 'rose',
  Rucksack: 'backpack',
  rufen: 'to call',
  Ruhe: 'quiet / silence',
  ruhig: 'quiet',
  rund: 'round',
  Rundgang: 'tour',
  'Rätsel': 'puzzle',
  'Rücken': 'back',
  Sache: 'thing',
  Saft: 'juice',
  sagen: 'to say',
  Salat: 'salad',
  Salz: 'salt',
  sammeln: 'to collect',
  Satz: 'sentence',
  sauber: 'clean',
  sauer: 'sour',
  schade: 'a pity / too bad',
  Schalter: 'counter / window',
  scheinen: 'to shine',
  schenken: 'to give (as a gift)',
  Schere: 'scissors',
  schicken: 'to send',
  Schiff: 'ship',
  schimpfen: 'to scold / grumble',
  Schirm: 'umbrella',
  schlafen: 'to sleep',
  Schlafzimmer: 'bedroom',
  schlecht: 'bad',
  'schließen': 'to close',
  schlimm: 'bad / serious',
  Schloss: 'castle',
  Schluss: 'end',
  'Schlüssel': 'key',
  schmecken: 'to taste',
  Schmerz: 'pain',
  schmutzig: 'dirty',
  Schnee: 'snow',
  'schneiden (sich)': 'to cut (oneself)',
  schneien: 'to snow',
  schnell: 'fast',
  Schokolade: 'chocolate',
  Schrank: 'cupboard / wardrobe',
  schreiben: 'to write',
  schriftlich: 'in writing',
  Schuh: 'shoe',
  Schule: 'school',
  schwach: 'weak',
  schwanger: 'pregnant',
  Schwein: 'pig',
  Schwimmbad: 'swimming pool',
  'schädlich': 'harmful',
  'schön': 'beautiful',
  'Schüler': 'pupil / student',
  'Schülerin': 'female pupil / student',
  sehen: 'to see',
  'Sehenswürdigkeit': 'sight / attraction',
  sehr: 'very',
  Seife: 'soap',
  Seite: 'page',
  Sendung: 'program / broadcast',
  Service: 'service',
  'setzen (sich)': 'to sit down',
  'sich umziehen': 'to change clothes',
  sicher: 'safe',
  singen: 'to sing',
  sitzen: 'to sit',
  Ski: 'ski',
  so: 'like this / so',
  Sofa: 'sofa',
  sofort: 'immediately',
  sollen: 'should / to be supposed to',
  Sonne: 'sun',
  sonnig: 'sunny',
  sonst: 'otherwise',
  spannend: 'exciting',
  'Spaß': 'fun',
  Speisekarte: 'menu',
  Spiel: 'game',
  spielen: 'to play',
  Sport: 'sport',
  sportlich: 'athletic / sporty',
  Sprache: 'language',
  sprechen: 'to speak',
  Sprechstunde: 'office hours / consultation',
  'spät': 'late',
  'später': 'later',
  Stadt: 'city',
  Stadtplan: 'city map',
  Star: 'star',
  stark: 'strong',
  stattfinden: 'to take place',
  stehen: 'to stand',
  stellen: 'to put / place',
  sterben: 'to die',
  Stift: 'pen / pencil',
  Stipendium: 'scholarship',
  Stock: 'floor / storey',
  Stockwerk: 'floor / storey',
  Strand: 'beach',
  'Straße': 'street',
  'Straßenbahn': 'tram',
  'streiten (sich)': 'to argue',
  Stress: 'stress',
  stressig: 'stressful',
  Student: 'student',
  studieren: 'to study',
  Studium: 'studies / degree program',
  Stuhl: 'chair',
  'stören': 'to disturb',
  'Stück': 'piece',
  suchen: 'to look for',
  super: 'great',
  Supermarkt: 'supermarket',
  Suppe: 'soup',
  'süß': 'sweet',
  'T-Shirt': 'T-shirt',
  Tablet: 'tablet',
  Tablette: 'pill / tablet',
  Tafel: 'board',
  tanzen: 'to dance',
  Tasche: 'bag',
  Tasse: 'cup',
  Taxi: 'taxi',
  Tee: 'tea',
  teilen: 'to share / divide',
  Telefon: 'telephone',
  telefonieren: 'to phone / call',
  Teller: 'plate',
  Tennis: 'tennis',
  Termin: 'appointment',
  teuer: 'expensive',
  Text: 'text',
  Ticket: 'ticket',
  tief: 'deep',
  Tipp: 'tip',
  Tisch: 'table',
  Titel: 'title',
  Toilette: 'toilet',
  toll: 'great',
  Tomate: 'tomato',
  Topf: 'pot',
  Torte: 'cake',
  tot: 'dead',
  total: 'totally',
  Tour: 'tour',
  Tourist: 'tourist',
  Touristin: 'tourist',
  tragen: 'to carry',
  Traum: 'dream',
  'treffen (sich)': 'to meet',
  trinken: 'to drink',
  trocken: 'dry',
  'tschüs': 'bye',
  tun: 'to do / hurt',
  typisch: 'typical',
  'Tür': 'door',
  Uhr: 'clock / o\'clock',
  um: 'at (time) / around',
  unbedingt: 'absolutely',
  und: 'and',
  Unfall: 'accident',
  'Universität': 'university',
  unter: 'under',
  'unterhalten (sich)': 'to chat / talk',
  Unterkunft: 'accommodation',
  Unterricht: 'lesson / class',
  Unterschrift: 'signature',
  untersuchen: 'to examine',
  'unterwegs sein': 'to be on the way',
  Urlaub: 'vacation / holiday',
  'verabredet sein': 'to have a date / appointment',
  verbieten: 'to forbid',
  'verboten sein': 'to be forbidden',
  verdienen: 'to earn',
  Verein: 'club / association',
  vergessen: 'to forget',
  vergleichen: 'to compare',
  verkaufen: 'to sell',
  Verkehr: 'traffic',
  Verkehrsmittel: 'means of transport',
  'verletzen (sich)': 'to injure / hurt oneself',
  'verlieben (sich)': 'to fall in love',
  Vermieter: 'landlord',
  Vermieterin: 'landlady',
  verreisen: 'to go on a trip',
  verschieben: 'to postpone',
  verschieden: 'different',
  verstehen: 'to understand',
  versuchen: 'to try',
  Vertrag: 'contract',
  vielleicht: 'maybe',
  Vogel: 'bird',
  voll: 'full',
  von: 'from / of',
  vor: 'before / in front of',
  vorbei: 'past / by',
  vorgestern: 'day before yesterday',
  vorher: 'beforehand',
  Vorname: 'first name',
  vorsichtig: 'careful',
  'vorwärts': 'forward',
  wach: 'awake',
  Wagen: 'car',
  wahrscheinlich: 'probably',
  wann: 'when',
  warm: 'warm',
  warten: 'to wait',
  warum: 'why',
  was: 'what',
  'waschen (sich)': 'to wash (oneself)',
  Wasser: 'water',
  wechseln: 'to change',
  Weg: 'way / path',
  weg: 'away / gone',
  'weg sein': 'to be away / gone',
  wegbringen: 'to take away',
  wegnehmen: 'to take away',
  wegwerfen: 'to throw away',
  wehtun: 'to hurt',
  weich: 'soft',
  Wein: 'wine',
  weinen: 'to cry',
  weiter: 'further / on',
  weiterhelfen: 'to help further',
  weitermachen: 'to continue',
  welcher: 'which',
  wenigstens: 'at least',
  wenn: 'if / when',
  wer: 'who',
  werden: 'to become',
  Werkstatt: 'garage / workshop',
  Wettbewerb: 'competition',
  Wetter: 'weather',
  wichtig: 'important',
  wie: 'how',
  wieder: 'again',
  'Wiederhören': 'goodbye (on the phone)',
  Wiedersehen: 'goodbye / farewell',
  willkommen: 'welcome',
  Wind: 'wind',
  windig: 'windy',
  wissen: 'to know',
  Witz: 'joke',
  witzig: 'funny',
  wo: 'where',
  woher: 'where from',
  wohin: 'where to',
  wohnen: 'to live',
  Wohnung: 'apartment',
  Wohnzimmer: 'living room',
  Wolke: 'cloud',
  wollen: 'to want',
  Workshop: 'workshop',
  Wort: 'word',
  'wählen': 'to choose / dial',
  'Wäsche': 'laundry',
  'wünschen': 'to wish',
  Zahl: 'number',
  zahlen: 'to pay',
  Zahn: 'tooth',
  zeichnen: 'to draw',
  zeigen: 'to show',
  Zeit: 'time',
  Zeitung: 'newspaper',
  Zelt: 'tent',
  Zentrum: 'center',
  Zettel: 'note / slip of paper',
  Ziel: 'goal / finish line',
  Zimmer: 'room',
  Zirkus: 'circus',
  Zitrone: 'lemon',
  zu: 'to',
  Zucker: 'sugar',
  zuerst: 'first / at first',
  Zug: 'train',
  'zurück': 'back',
  'zurück-': 'back-',
  zusammen: 'together',
  zwischen: 'between',
  'ärgern (sich)': 'to get angry',
  'öffnen': 'to open',
  'Öl': 'oil',
  'über': 'over / above',
  'überall': 'everywhere',
  'übermorgen': 'day after tomorrow',
  'übernachten': 'to stay overnight',
  'übersetzen': 'to translate',
  'Übersetzung': 'translation',
};

// --- part-of-speech inference ----------------------------------------------

const ADJECTIVES = new Set([
  'arbeitslos',
  'besetzt',
  'beste',
  'dick',
  'dumm',
  'geboren',
  'geschlossen',
  'herzlich',
  'hübsch',
  'jung',
  'kreativ',
  'leicht',
  'lieb',
  'möglich',
  'nächste',
  'normal',
  'offen',
  'praktisch',
  'schwer',
  'sympathisch',
  'traurig',
  'verrückt',
  'wahr',
  'weit',
  'wunderbar',
]);

const ADVERBS = new Set([
  'besonders',
  'deshalb',
  'genug',
  'hoffentlich',
  'lange',
  'lieber',
  'schon',
  'wenig',
  'wirklich',
]);

function inferPos(lemma, article) {
  if (article) return 'noun';
  const lower = lemma.toLowerCase();
  if (ADJECTIVES.has(lower)) return 'adj';
  if (ADVERBS.has(lower)) return 'adv';
  // verb: a (multi-word) lemma whose last token is an infinitive
  const last = lemma.split(/\s+/).pop();
  if (last.length > 3 && /(en|ln|rn)$/.test(last)) return 'verb';
  if (['sein', 'tun', 'haben', 'gehen'].includes(last)) return 'verb';
  return 'other';
}

// --- merge helpers ----------------------------------------------------------

function uniq(arr) {
  return [...new Set(arr)];
}

const SOURCE_ORDER = ['telc-a1.1', 'telc-a1.2', 'goethe'];
function orderSources(arr) {
  const known = SOURCE_ORDER.filter((s) => arr.includes(s));
  const unknown = arr.filter((s) => !SOURCE_ORDER.includes(s)).sort();
  return [...known, ...unknown];
}

// --- build ------------------------------------------------------------------

function build() {
  const SOURCES = discoverSources();

  // Flatten all source entries, normalizing lemma and remembering origin tag/level.
  const rows = [];
  for (const { file, tag, level } of SOURCES) {
    const data = JSON.parse(readFileSync(join(SRC, file), 'utf8'));
    for (const e of data) {
      const { lemma, pluralFromNote, singularOnly } = normalizeLemma(e.lemma);
      rows.push({
        tag,
        level,
        lemma,
        article: e.article ?? null,
        plural: singularOnly ? null : (e.plural ?? pluralFromNote ?? null),
        en: (e.en ?? '').trim(),
        examples: Array.isArray(e.examples) ? e.examples : [],
        categories: Array.isArray(e.categories) ? e.categories : [],
      });
    }
  }

  // Group by slug.
  const groups = new Map();
  for (const r of rows) {
    const id = slug(r.lemma);
    if (!groups.has(id)) groups.set(id, []);
    groups.get(id).push(r);
  }

  const changelog = [];
  const words = [];

  for (const [id, group] of groups) {
    // Canonical lemma: prefer Telc casing, in source order.
    const byOrder = [...group].sort(
      (a, b) => SOURCE_ORDER.indexOf(a.tag) - SOURCE_ORDER.indexOf(b.tag),
    );
    const lemma = byOrder[0].lemma;

    // Article: Goethe's r/e/s marker wins ties; else first non-null (Telc order).
    const goethe = group.find((r) => r.tag === 'goethe');
    let article =
      goethe && goethe.article
        ? goethe.article
        : (byOrder.find((r) => r.article)?.article ?? null);

    // Plural: prefer an explicit Telc full form, then Goethe.
    const plural = byOrder.find((r) => r.plural)?.plural ?? null;

    // English: first non-empty in Telc order, else baked Goethe translation.
    let en = byOrder.find((r) => r.en)?.en ?? '';
    if (!en && GOETHE_EN[lemma] !== undefined) en = GOETHE_EN[lemma];

    // Apply "only obvious" corrections.
    let corrected = false;
    if (CORRECTIONS[lemma] !== undefined && en !== CORRECTIONS[lemma]) {
      changelog.push({ lemma, from: en, to: CORRECTIONS[lemma] });
      en = CORRECTIONS[lemma];
      corrected = true;
    }

    if (!en) {
      throw new Error(
        `No English for "${lemma}" (id=${id}). Add it to GOETHE_EN.`,
      );
    }

    const sources = orderSources(uniq(group.map((r) => r.tag)));
    const levels = [...new Set(group.map((r) => r.level))].sort();
    const examples = uniq(
      byOrder
        .flatMap((r) => r.examples)
        .map((s) => s.trim())
        .filter(Boolean),
    );

    const word = {
      id,
      lemma,
      article,
      plural,
      en,
      pos: inferPos(lemma, article),
      examples,
      sources,
      levels,
    };
    if (corrected) word.corrected = true;
    words.push(word);
  }

  words.sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
  changelog.sort((a, b) =>
    a.lemma < b.lemma ? -1 : a.lemma > b.lemma ? 1 : 0,
  );

  writeFileSync(
    join(ROOT, 'data', 'words.json'),
    JSON.stringify(words, null, 2) + '\n',
  );
  writeFileSync(
    join(ROOT, 'data', 'changelog.json'),
    JSON.stringify(changelog, null, 2) + '\n',
  );

  // Sanity summary.
  const dupes = words.length !== new Set(words.map((w) => w.id)).size;
  console.log(
    `words: ${words.length}  changelog: ${changelog.length}  dupe ids: ${dupes}`,
  );
  const posCounts = {};
  for (const w of words) posCounts[w.pos] = (posCounts[w.pos] || 0) + 1;
  console.log('pos:', posCounts);
}

build();
